### ISSUE TITLE
normaliseqPCR across experimental replicates

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#34]
Currently, the normaliseqPCR function only groups by Sample. Therefore, if you are trying to normalise the same construct to the same control but for two or more experimental replicates the function doesn't work as expected. The function will group all the control's Ct values and calculate a cross-experiment median to normalise all construct's Ct. Instead, if provided with a another variable,  s.a. "exp_rep", the function should normalise the constructs by the median of their respective experimental controls.

**Comment by ewallace** [comment]
As we discussed, tidyqpcr treats replicates as different samples, and so something `exp_rep` should be incorporated in the `Sample` variable. Other information about samples can be stored in other variables, e.g. `Strain`, `Condition`, etc., depending on the experiment. This is now explained better (hopefully) in the plate setup vignette as updated in #20.

We should still:

* explain in the documentation for normaliseqPCR
* give the `group_by` parameter as an argument with default value `Sample`, so that expert users can group differently if they choose.

**Comment by ewallace** [comment]
This is explained in the documentation for normalizeqPCR.

@DimmestP and I discussed, and we are not going to implement `group_by` as an argument for now.
