### ISSUE TITLE
Tibbles all the way - document

### ISSUE THREAD

**Issue by ewallace** [ewallace/tidyqpcr#57]
README and paper #44 should highlight the approach that *everything is a tibble / data frame* so that users only have to learn one standard kind of object. This contrasts with earlier qPCR R packages that use S4 classes and have many different kinds of objects.

**Comment by ewallace** [comment]
Action point: write this into the paper introduction, then close issue.

**Comment by ewallace** [comment]
I think this is now clear.

**Comment by ramiromagno** [comment]
While it might be nice to have tibbles all the way, I think there needs to be some sort of standard format, so that functions know what columns to expect.

Let us consider amplification curves. I think it would be nice to keep the number of columns to a minimum: `plate`, `well`, `cycle`, and `fluor`. And perhaps leave sample id and target id to other tibbles. These would be metadata tibbles. And if needed a join could be made to cross over information.
